/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NotePackPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian10 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  teamFolder: "Team",
  todoAnchorTitle: "Open Todos",
  recentFilesAnchorTitle: "Recent Files",
  anchorHeadingLevel: "##",
  todoGroupHeadingLevel: "####",
  recentFilesCount: 5,
  endOfDayHour: 17,
  endOfWeekDay: 6,
  showUndatedFirst: false
};
var VIEW_TYPE_MY_TODOS = "notepack-my-todos";
var VIEW_TYPE_TEAM_TODOS = "notepack-team-todos";
var VIEW_TYPE_RECENT_FILES = "notepack-recent-files";

// src/lib/todoIndex.ts
var import_obsidian2 = require("obsidian");

// src/utility/team.ts
var import_obsidian = require("obsidian");
function formatAlias(alias) {
  return alias.replace(/\s/g, ".").toLowerCase();
}
function getTeamMembers(app, settings) {
  const teamFolderPath = settings.teamFolder;
  const teamFolder = app.vault.getAbstractFileByPath(teamFolderPath);
  if (!(teamFolder instanceof import_obsidian.TFolder)) {
    return [];
  }
  const members = [];
  for (const child of teamFolder.children) {
    if (!(child instanceof import_obsidian.TFolder)) continue;
    if (child.path.toLowerCase().includes("archive")) continue;
    const name = child.name;
    const readmePath = (0, import_obsidian.normalizePath)(`${child.path}/README.md`);
    const readmeFile = app.vault.getAbstractFileByPath(readmePath);
    let aliases = [];
    let isNonReporting = false;
    if (readmeFile instanceof import_obsidian.TFile) {
      const cache = app.metadataCache.getFileCache(readmeFile);
      if (cache == null ? void 0 : cache.frontmatter) {
        if (Array.isArray(cache.frontmatter.aliases)) {
          aliases = cache.frontmatter.aliases;
        }
        if (cache.frontmatter.isNonReporting) {
          isNonReporting = true;
        }
      }
    }
    members.push({ name, aliases, isNonReporting });
  }
  return members;
}
function getMentionOnlyNames(folderMembers, assignedNames) {
  const folderNames = new Set(folderMembers.map((m) => m.name));
  return assignedNames.filter((n) => !folderNames.has(n));
}
function getAllTeamMembers(folderMembers, assignedNames) {
  const mentionOnly = getMentionOnlyNames(folderMembers, assignedNames);
  return [
    ...folderMembers,
    ...mentionOnly.map((name) => ({ name, aliases: [], isNonReporting: false }))
  ].sort((a, b) => a.name.localeCompare(b.name));
}
function getTeamMemberAliases(app, settings) {
  const members = getTeamMembers(app, settings);
  const map = {};
  for (const member of members) {
    map[formatAlias(member.name)] = member.name;
    for (const alias of member.aliases) {
      map[formatAlias(alias)] = member.name;
    }
  }
  return map;
}

// src/utility/dueDateParser.ts
var MS_PER_DAY = 1e3 * 60 * 60 * 24;
var DAYS_PER_WEEK = 7;
var MONTHS_PER_QUARTER = 3;
var SOON_THRESHOLD_DAYS = 7;
var WEEKDAY_DISPLAY_DAYS = 6;
var JANUARY = 0;
var DECEMBER = 11;
var MONTH_NAMES = {
  january: 0,
  jan: 0,
  february: 1,
  feb: 1,
  march: 2,
  mar: 2,
  april: 3,
  apr: 3,
  may: 4,
  june: 5,
  jun: 5,
  july: 6,
  jul: 6,
  august: 7,
  aug: 7,
  september: 8,
  sep: 8,
  sept: 8,
  october: 9,
  oct: 9,
  november: 10,
  nov: 10,
  december: 11,
  dec: 11
};
var WEEKDAY_NAMES = {
  sunday: 0,
  sun: 0,
  monday: 1,
  mon: 1,
  tuesday: 2,
  tue: 2,
  wednesday: 3,
  wed: 3,
  thursday: 4,
  thu: 4,
  friday: 5,
  fri: 5,
  saturday: 6,
  sat: 6
};
var MONTH_RE = `jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?`;
var WEEKDAY_RE = `monday|mon|tuesday|tue|wednesday|wed|thursday|thu|friday|fri|saturday|sat|sunday|sun`;
var ISO_DATE_RE = `\\d{4}-\\d{2}-\\d{2}`;
var SLASH_DATE_RE = `\\d{1,2}\\/\\d{1,2}(?:\\/\\d{4})?`;
var MONTH_DAY_RE = `(?:${MONTH_RE})\\s+\\d{1,2}(?:st|nd|rd|th)?(?:[,\\s]+\\d{4})?`;
var NEXT_PERIOD_RE = `next\\s+(?:week|month|year)`;
var END_OF_NEXT_RE = `end[\\s\\-]of[\\s\\-]next[\\s\\-](?:week|month|year)`;
var END_OF_MONTH_NAME_RE = `end[\\s\\-]of[\\s\\-](?:${MONTH_RE})`;
var OPTIONAL_NEXT_WEEKDAY_RE = `(?:next\\s+)?(?:${WEEKDAY_RE})`;
var SIMPLE_DATE = `today|tomorrow|${NEXT_PERIOD_RE}|${END_OF_NEXT_RE}|end[\\s\\-]of[\\s\\-](?:week|month|year)|${END_OF_MONTH_NAME_RE}|${OPTIONAL_NEXT_WEEKDAY_RE}|${ISO_DATE_RE}|${SLASH_DATE_RE}|${MONTH_DAY_RE}`;
var DATE_CHUNK = `(?:${ISO_DATE_RE}|${SLASH_DATE_RE}|${MONTH_DAY_RE}|today|tomorrow|${NEXT_PERIOD_RE}|${OPTIONAL_NEXT_WEEKDAY_RE}|eod\\s+(?:${SIMPLE_DATE})|end[\\s\\-]of[\\s\\-]day\\s+(?:${SIMPLE_DATE})|eod|eow|eom|eoq|eoy|${END_OF_NEXT_RE}|end[\\s\\-]of[\\s\\-](?:day|week|month|quarter|year)|${END_OF_MONTH_NAME_RE})`;
var DUE_PATTERNS = [
  new RegExp(`\\bdue\\s+(?:by|on|at|before)\\s+(${DATE_CHUNK})`, "i"),
  new RegExp(`\\bdue\\s+(${DATE_CHUNK})`, "i"),
  new RegExp(`\\bby\\s+(${DATE_CHUNK})`, "i"),
  new RegExp(`\\bbefore\\s+(${DATE_CHUNK})`, "i"),
  new RegExp(`\\bon\\s+(${DATE_CHUNK})`, "i")
];
function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function atEndOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59);
}
function daysDiff(a, b) {
  return Math.round((startOfDay(a).getTime() - startOfDay(b).getTime()) / MS_PER_DAY);
}
function parseAbsoluteDate(str, ref, endOfDayHour, endOfWeekDay) {
  const s = str.trim().toLowerCase();
  if (s === "today") return startOfDay(ref);
  if (s === "tomorrow") {
    const d = startOfDay(ref);
    d.setDate(d.getDate() + 1);
    return d;
  }
  if (s === "eod" || s === "end of day" || s === "end-of-day") {
    return new Date(ref.getFullYear(), ref.getMonth(), ref.getDate(), endOfDayHour, 0, 0);
  }
  const eodCompoundMatch = s.match(/^(?:eod|end[\s-]of[\s-]day)\s+(.+)$/);
  if (eodCompoundMatch) {
    const baseDate = parseAbsoluteDate(eodCompoundMatch[1], ref, endOfDayHour, endOfWeekDay);
    if (baseDate) {
      return new Date(baseDate.getFullYear(), baseDate.getMonth(), baseDate.getDate(), endOfDayHour, 0, 0);
    }
  }
  const endOfNextMatch = s.match(/^end[\s-]of[\s-]next[\s-](week|month|year)$/);
  if (endOfNextMatch) {
    const unit = endOfNextMatch[1];
    if (unit === "week") {
      const d = startOfDay(ref);
      const daysUntilEOW = (endOfWeekDay - d.getDay() + DAYS_PER_WEEK) % DAYS_PER_WEEK;
      return atEndOfDay(new Date(d.getFullYear(), d.getMonth(), d.getDate() + daysUntilEOW + DAYS_PER_WEEK));
    }
    if (unit === "month") {
      return atEndOfDay(new Date(ref.getFullYear(), ref.getMonth() + 2, 0));
    }
    return atEndOfDay(new Date(ref.getFullYear() + 1, DECEMBER, 31));
  }
  if (s === "eow" || s === "end of week" || s === "end-of-week") {
    const d = startOfDay(ref);
    const daysUntilEOW = (endOfWeekDay - d.getDay() + DAYS_PER_WEEK) % DAYS_PER_WEEK;
    return atEndOfDay(new Date(d.getFullYear(), d.getMonth(), d.getDate() + daysUntilEOW));
  }
  if (s === "eom" || s === "end of month" || s === "end-of-month") {
    return atEndOfDay(new Date(ref.getFullYear(), ref.getMonth() + 1, 0));
  }
  const endOfMonthNameMatch = s.match(new RegExp(`^end[\\s-]of[\\s-](${MONTH_RE})$`));
  if (endOfMonthNameMatch) {
    const month = MONTH_NAMES[endOfMonthNameMatch[1]];
    return atEndOfDay(new Date(ref.getFullYear(), month + 1, 0));
  }
  if (s === "eoq" || s === "end of quarter" || s === "end-of-quarter") {
    const quarterEndMonth = Math.floor(ref.getMonth() / MONTHS_PER_QUARTER) * MONTHS_PER_QUARTER + (MONTHS_PER_QUARTER - 1);
    return atEndOfDay(new Date(ref.getFullYear(), quarterEndMonth + 1, 0));
  }
  if (s === "eoy" || s === "end of year" || s === "end-of-year") {
    return atEndOfDay(new Date(ref.getFullYear(), DECEMBER, 31));
  }
  if (s === "next week") {
    const d = startOfDay(ref);
    const startOfWeekDay = (endOfWeekDay + 1) % DAYS_PER_WEEK;
    const daysIntoWeek = (d.getDay() - startOfWeekDay + DAYS_PER_WEEK) % DAYS_PER_WEEK;
    d.setDate(d.getDate() - daysIntoWeek + DAYS_PER_WEEK);
    return d;
  }
  if (s === "next month") {
    return new Date(ref.getFullYear(), ref.getMonth() + 1, 1);
  }
  if (s === "next year") {
    return new Date(ref.getFullYear() + 1, JANUARY, 1);
  }
  const weekdayMatch = s.match(
    new RegExp(`^(next\\s+)?(${WEEKDAY_RE})$`)
  );
  if (weekdayMatch) {
    const hasNext = !!weekdayMatch[1];
    const target = WEEKDAY_NAMES[weekdayMatch[2]];
    const today = startOfDay(ref);
    if (hasNext) {
      const daysUntilNextSunday = (DAYS_PER_WEEK - today.getDay()) % DAYS_PER_WEEK || DAYS_PER_WEEK;
      const d2 = new Date(today);
      d2.setDate(today.getDate() + daysUntilNextSunday + target);
      return d2;
    }
    let diff = target - today.getDay();
    if (diff <= 0) diff += DAYS_PER_WEEK;
    const d = new Date(today);
    d.setDate(d.getDate() + diff);
    return d;
  }
  const isoMatch = str.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (isoMatch) {
    return new Date(parseInt(isoMatch[1]), parseInt(isoMatch[2]) - 1, parseInt(isoMatch[3]));
  }
  const slashMatch = str.match(/^(\d{1,2})\/(\d{1,2})(?:\/(\d{4}))?$/);
  if (slashMatch) {
    const year = slashMatch[3] ? parseInt(slashMatch[3]) : ref.getFullYear();
    return new Date(year, parseInt(slashMatch[1]) - 1, parseInt(slashMatch[2]));
  }
  const monthMatch = s.match(
    new RegExp(`^(${MONTH_RE})\\s+(\\d{1,2})(?:st|nd|rd|th)?(?:[,\\s]+(\\d{4}))?$`)
  );
  if (monthMatch) {
    const month = MONTH_NAMES[monthMatch[1]];
    const day = parseInt(monthMatch[2]);
    const year = monthMatch[3] ? parseInt(monthMatch[3]) : ref.getFullYear();
    return new Date(year, month, day);
  }
  return null;
}
function parseDateString(dateStr) {
  var _a, _b;
  const parts = dateStr.split("-").map(Number);
  return new Date(parts[0], ((_a = parts[1]) != null ? _a : 1) - 1, (_b = parts[2]) != null ? _b : 1, 12, 0, 0);
}
function parseDueDate(text, referenceDate = /* @__PURE__ */ new Date(), endOfDayHour = 17, endOfWeekDay = 6) {
  text = text.replace(/\*{1,2}|_{1,2}|~{2}|`|={2}/g, "");
  for (const pattern of DUE_PATTERNS) {
    const match = text.match(pattern);
    if (match) {
      const parsed = parseAbsoluteDate(match[1], referenceDate, endOfDayHour, endOfWeekDay);
      if (parsed) return parsed;
    }
  }
  return null;
}
function getDueDateStatus(date) {
  const now = /* @__PURE__ */ new Date();
  const diff = daysDiff(date, now);
  if (diff < 0) return "overdue";
  if (diff === 0) {
    if (date.getHours() !== 0 || date.getMinutes() !== 0) {
      return date <= now ? "overdue" : "today";
    }
    return "today";
  }
  if (diff <= SOON_THRESHOLD_DAYS) return "soon";
  return "future";
}
function getOverdueDays(date) {
  const now = /* @__PURE__ */ new Date();
  const diff = daysDiff(date, now);
  if (diff < 0) return Math.max(1, Math.abs(diff));
  if (diff === 0 && (date.getHours() !== 0 || date.getMinutes() !== 0) && date <= now) {
    return 1;
  }
  return null;
}
function formatOverdueDays(days) {
  if (days < 14) return `${days}d`;
  if (days < 60) return `${Math.floor(days / 7)}w`;
  return `${Math.floor(days / 30)}mo`;
}
function formatDueDate(date) {
  const now = /* @__PURE__ */ new Date();
  const d = startOfDay(date);
  const diff = daysDiff(date, now);
  if (diff === 0) return "Today";
  if (diff === 1) return "Tomorrow";
  if (diff === -1) return "Yesterday";
  if (diff > 1 && diff <= WEEKDAY_DISPLAY_DAYS) return d.toLocaleDateString("en-US", { weekday: "long" });
  if (d.getFullYear() === now.getFullYear()) {
    return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  }
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

// src/lib/todoIndex.ts
var TodoIndex = class {
  constructor(app, settings) {
    /** file.path → Todo[] */
    this.index = /* @__PURE__ */ new Map();
    /** Cached alias map, rebuilt when team data changes */
    this.aliasMap = {};
    /** Monotonically increasing ID counter */
    this.nextId = 1;
    /** Listeners notified after any index mutation */
    this.listeners = /* @__PURE__ */ new Set();
    this.app = app;
    this.settings = settings;
  }
  // -------------------------------------------------------------------
  // Public API
  // -------------------------------------------------------------------
  /**
   * Full rebuild: clear everything and re-index all markdown files.
   * Called on plugin load and when settings change.
   */
  async rebuild() {
    this.index.clear();
    this.nextId = 1;
    this.aliasMap = getTeamMemberAliases(this.app, this.settings);
    const files = this.app.vault.getMarkdownFiles();
    await Promise.all(
      files.filter((file) => this.isFileInScope(file) && !this.isReadme(file)).map((file) => this.indexFile(file))
    );
    this.notify();
  }
  /**
   * Refresh the alias map (e.g. when a team README.md changes).
   * Re-resolves aliases for all existing todos without re-reading files.
   */
  refreshAliases() {
    this.aliasMap = getTeamMemberAliases(this.app, this.settings);
    for (const [, todos] of this.index) {
      for (const todo of todos) {
        todo.assignedToAlias = this.resolveAlias(todo.assignedTo);
      }
    }
    this.notify();
  }
  /**
   * Incrementally update the index for a single file.
   * Called from the metadataCache 'changed' event handler.
   */
  async updateFile(file, _data, cache) {
    if (this.isReadme(file)) {
      if (file.path.startsWith((0, import_obsidian2.normalizePath)(this.settings.teamFolder) + "/")) {
        this.refreshAliases();
      }
      return;
    }
    if (!this.isFileInScope(file)) {
      if (this.index.has(file.path)) {
        this.index.delete(file.path);
        this.notify();
      }
      return;
    }
    await this.indexFile(file, cache, _data);
    this.notify();
  }
  /**
   * Remove a file from the index (on delete/rename).
   */
  removeFile(path) {
    if (this.index.has(path)) {
      this.index.delete(path);
      this.notify();
    }
  }
  /**
   * Get all todos across the vault.
   */
  getAllTodos() {
    const all = [];
    for (const todos of this.index.values()) {
      all.push(...todos);
    }
    return this.sortTodos(all);
  }
  /**
   * Get todos assigned to a specific person (by alias or name).
   */
  getTodosFor(assignment) {
    const resolved = this.resolveAlias(assignment);
    return this.sortTodos(
      this.getAllTodos().filter((t) => t.assignedToAlias === resolved)
    );
  }
  /**
   * Get todos assigned to "Me" (unassigned todos).
   */
  getMyTodos() {
    return this.sortTodos(
      this.getAllTodos().filter((t) => t.assignedToAlias === "Me")
    );
  }
  /**
   * Get all unique assignee names from indexed todos, excluding "Me".
   * Sorted alphabetically for stable display order.
   */
  getAssignedNames() {
    const names = /* @__PURE__ */ new Set();
    for (const todos of this.index.values()) {
      for (const todo of todos) {
        if (todo.assignedToAlias !== "Me") {
          names.add(todo.assignedToAlias);
        }
      }
    }
    return [...names].sort((a, b) => a.localeCompare(b));
  }
  /**
   * Get todos that fall within a specific folder path.
   */
  getTodosInFolder(folderPath) {
    const all = [];
    for (const [path, todos] of this.index) {
      if (path.startsWith((0, import_obsidian2.normalizePath)(folderPath) + "/") || path === (0, import_obsidian2.normalizePath)(folderPath)) {
        all.push(...todos);
      }
    }
    return this.sortTodos(all);
  }
  /**
   * Get unique group names from a set of todos, ordered by date descending.
   */
  getGroupNames(todos) {
    const undatedFirst = this.settings.showUndatedFirst;
    const sorted = [...todos].sort((a, b) => {
      if (a.fileDate && b.fileDate) return b.fileDate.localeCompare(a.fileDate);
      if (a.fileDate && !b.fileDate) return undatedFirst ? 1 : -1;
      if (!a.fileDate && b.fileDate) return undatedFirst ? -1 : 1;
      return b.fileMtime - a.fileMtime;
    });
    const seen = /* @__PURE__ */ new Set();
    const groups = [];
    for (const todo of sorted) {
      if (!seen.has(todo.groupName)) {
        seen.add(todo.groupName);
        groups.push(todo.groupName);
      }
    }
    return groups;
  }
  /**
   * Subscribe to index changes. Returns an unsubscribe function.
   */
  onChange(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }
  /** Update settings reference (called when settings change). */
  updateSettings(settings) {
    this.settings = settings;
  }
  // -------------------------------------------------------------------
  // Internal
  // -------------------------------------------------------------------
  notify() {
    for (const listener of this.listeners) {
      listener();
    }
  }
  /**
   * Index a single file by reading its cache (or fetching it).
   */
  async indexFile(file, cache, data) {
    var _a;
    const fileCache = cache || this.app.metadataCache.getFileCache(file);
    if ((_a = fileCache == null ? void 0 : fileCache.frontmatter) == null ? void 0 : _a.excludeTodos) {
      this.index.delete(file.path);
      return;
    }
    const todos = [];
    const listItems = fileCache == null ? void 0 : fileCache.listItems;
    if (!listItems) {
      this.index.set(file.path, []);
      return;
    }
    const content = data != null ? data : await this.app.vault.cachedRead(file);
    if (!content) {
      this.index.set(file.path, []);
      return;
    }
    const lines = content.split("\n");
    const fileDate = this.extractFileDate(file.name);
    const refDate = fileDate ? parseDateString(fileDate) : /* @__PURE__ */ new Date();
    for (const item of listItems) {
      if (item.task !== " ") continue;
      const lineNum = item.position.start.line;
      if (lineNum >= lines.length) continue;
      const line = lines[lineNum];
      const todoMatch = line.match(/^[\s]*-\s?\[ \]\s?(.*)/);
      if (!todoMatch) continue;
      const rawText = todoMatch[1].trim();
      const assignedTo = this.getAssignment(rawText);
      const assignedToAlias = this.resolveAlias(assignedTo);
      todos.push({
        id: this.nextId++,
        file,
        groupName: this.buildGroupName(file),
        text: rawText,
        assignedTo,
        assignedToAlias,
        fileMtime: file.stat.mtime,
        fileDate,
        lineNumber: lineNum,
        dueDate: parseDueDate(rawText, refDate, this.settings.endOfDayHour, this.settings.endOfWeekDay)
      });
    }
    this.index.set(file.path, todos);
  }
  /**
   * Determine if a file is within the configured scan scope.
   */
  isFileInScope(file) {
    if (file.path.toLowerCase().includes("archive")) return false;
    return true;
  }
  isReadme(file) {
    return file.name === "README.md";
  }
  /**
   * Parse the @mention assignment from a todo's text.
   * Returns "Me" for unassigned todos.
   */
  getAssignment(text) {
    const match = text.match(/^@([A-Za-z.]+)/);
    return match ? match[1] : "Me";
  }
  /**
   * Resolve an assignment string to a canonical team member name.
   */
  resolveAlias(assignment) {
    if (assignment === "Me") return "Me";
    const formatted = formatAlias(assignment.replace(/^@/, "").replace(/\./g, " "));
    return this.aliasMap[formatted] || assignment.replace(/\./g, " ");
  }
  /**
   * Extract a YYYY-MM-DD date prefix from a filename.
   */
  extractFileDate(filename) {
    const match = filename.match(/^(\d{4}(-\d{2}){0,2})/);
    return match ? match[1] : null;
  }
  /**
   * Build a display group name: "ParentFolder / FileStem"
   * If the parent folder name matches the file stem, go up one level.
   */
  buildGroupName(file) {
    const stem = file.basename;
    const parts = file.path.split("/");
    parts.pop();
    let parentName = parts.length > 0 ? parts[parts.length - 1] : "";
    if (parentName === stem && parts.length > 1) {
      parentName = parts[parts.length - 2];
    }
    if (!parentName) return stem;
    return `${parentName} / ${stem}`;
  }
  sortTodos(todos) {
    const undatedFirst = this.settings.showUndatedFirst;
    return todos.sort((a, b) => {
      if (a.fileDate && b.fileDate) {
        const cmp = b.fileDate.localeCompare(a.fileDate);
        if (cmp !== 0) return cmp;
      } else if (a.fileDate && !b.fileDate) {
        return undatedFirst ? 1 : -1;
      } else if (!a.fileDate && b.fileDate) {
        return undatedFirst ? -1 : 1;
      }
      return a.id - b.id;
    });
  }
};

// src/lib/todoExporter.ts
var import_obsidian3 = require("obsidian");
var TodoExporter = class {
  constructor(app, settings, todoIndex) {
    this.app = app;
    this.settings = settings;
    this.todoIndex = todoIndex;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Export everything: todos to all README.md files + recent files to root README.
   */
  async exportAll() {
    let count = 0;
    count += await this.exportTodosForPerson("Me");
    const members = getTeamMembers(this.app, this.settings);
    for (const member of members) {
      count += await this.exportTodosForPerson(member.name);
    }
    count += await this.exportTodosForFolders();
    await this.exportRecentFiles();
    new import_obsidian3.Notice(`NotePack: Exported todos to ${count} README file(s)`);
  }
  /**
   * Export todos assigned to a person into their README.md.
   * "Me" writes to the vault root README.md.
   * Named persons write to Team/<Name>/README.md.
   */
  async exportTodosForPerson(assignedTo) {
    let readmePath;
    if (assignedTo.toLowerCase() === "me") {
      readmePath = "README.md";
    } else {
      readmePath = (0, import_obsidian3.normalizePath)(`${this.settings.teamFolder}/${assignedTo}/README.md`);
    }
    const todos = assignedTo.toLowerCase() === "me" ? this.todoIndex.getMyTodos() : this.todoIndex.getTodosFor(assignedTo);
    return await this.writeTodosToReadme(readmePath, todos) ? 1 : 0;
  }
  /**
   * Recursively find all README.md files in the vault and write
   * folder-scoped todos into each one.
   */
  async exportTodosForFolders() {
    const root = this.app.vault.getRoot();
    return this.exportFolderRecursive(root);
  }
  async exportFolderRecursive(folder) {
    let count = 0;
    for (const child of folder.children) {
      if (!(child instanceof import_obsidian3.TFolder)) continue;
      if (child.path.toLowerCase().includes("archive")) continue;
      if (child.path.startsWith((0, import_obsidian3.normalizePath)(this.settings.teamFolder) + "/")) continue;
      const readmePath = (0, import_obsidian3.normalizePath)(`${child.path}/README.md`);
      const readmeFile = this.app.vault.getAbstractFileByPath(readmePath);
      if (readmeFile instanceof import_obsidian3.TFile) {
        const todos = this.todoIndex.getTodosInFolder(child.path);
        if (await this.writeTodosToReadme(readmePath, todos)) {
          count++;
        }
      }
      count += await this.exportFolderRecursive(child);
    }
    return count;
  }
  /**
   * Write recent files into the root README.md.
   */
  async exportRecentFiles() {
    const readmePath = "README.md";
    const readmeFile = this.app.vault.getAbstractFileByPath(readmePath);
    if (!(readmeFile instanceof import_obsidian3.TFile)) return;
    const recentFiles = this.getRecentFiles();
    const anchor = `${this.settings.anchorHeadingLevel} ${this.settings.recentFilesAnchorTitle}`;
    const recentSection = recentFiles.map((f) => {
      const relativePath = f.path;
      const encoded = encodeURIComponent(relativePath).replace(/%2F/g, "/").replace(/%3A/g, ":").replace(/%2B/g, "+").replace(/%2C/g, ",");
      return `* [${f.name}](${encoded})`;
    }).join("\n");
    const content = `${anchor}
${recentSection}
`;
    await this.app.vault.process(
      readmeFile,
      (src) => this.replaceSectionInSource(src, anchor, content)
    );
  }
  /**
   * Get the N most recently modified markdown files in the base folders.
   */
  getRecentFiles() {
    const allFiles = this.app.vault.getMarkdownFiles();
    return allFiles.filter((f) => {
      if (f.name === "README.md") return false;
      if (f.path.toLowerCase().includes("archive")) return false;
      return true;
    }).sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, this.settings.recentFilesCount);
  }
  /**
   * Write a set of todos into a README.md file, replacing the todo section.
   */
  async writeTodosToReadme(readmePath, todos) {
    const file = this.app.vault.getAbstractFileByPath(readmePath);
    if (!(file instanceof import_obsidian3.TFile)) return false;
    const anchor = `${this.settings.anchorHeadingLevel} ${this.settings.todoAnchorTitle}`;
    const todosContent = this.buildGroupedTodosString(todos, readmePath, anchor);
    await this.app.vault.process(
      file,
      (src) => this.replaceSectionInSource(src, anchor, todosContent)
    );
    return true;
  }
  /**
   * Build the grouped todos markdown string for a README.md file.
   */
  buildGroupedTodosString(todos, readmePath, prefix) {
    const groupNames = this.todoIndex.getGroupNames(todos);
    let result = `${prefix}
`;
    for (const group of groupNames) {
      const groupTodos = todos.filter((t) => t.groupName === group).sort((a, b) => a.id - b.id);
      if (groupTodos.length === 0) continue;
      const firstTodo = groupTodos[0];
      const relativePath = this.relativeEncodedPath(
        readmePath,
        firstTodo.file.path
      );
      result += `
${this.settings.todoGroupHeadingLevel} [${group}](${relativePath})
`;
      for (const todo of groupTodos) {
        result += `- [ ] ${todo.text}
`;
      }
    }
    return result;
  }
  /**
   * Replace a heading section in a source string.
   * If the anchor doesn't exist, appends to the end.
   */
  replaceSectionInSource(src, anchor, newContent) {
    const headingLevel = this.settings.anchorHeadingLevel;
    const start = src.indexOf(anchor);
    if (start === -1) {
      return src.trimEnd() + "\n\n" + newContent.trimEnd() + "\n";
    }
    const afterAnchor = src.substring(start + anchor.length);
    const nextHeadingMatch = afterAnchor.indexOf(`
${headingLevel} `);
    const end = nextHeadingMatch === -1 ? src.length : start + anchor.length + nextHeadingMatch;
    const before = src.substring(0, start).trimEnd();
    const after = src.substring(end).trimStart();
    const parts = [before, newContent.trimEnd()];
    if (after) parts.push(after);
    return parts.join("\n\n") + "\n";
  }
  /**
   * Build a relative, URI-encoded path from one file to another.
   */
  relativeEncodedPath(fromPath, toPath) {
    const fromDir = fromPath.substring(0, fromPath.lastIndexOf("/")) || ".";
    const fromParts = fromDir === "." ? [] : fromDir.split("/");
    const toParts = toPath.split("/");
    let common = 0;
    while (common < fromParts.length && common < toParts.length && fromParts[common] === toParts[common]) {
      common++;
    }
    const ups = fromParts.length - common;
    const relative = [
      ...Array(ups).fill(".."),
      ...toParts.slice(common)
    ].join("/");
    return encodeURIComponent(relative).replace(/%2F/g, "/").replace(/%3A/g, ":").replace(/%2B/g, "+").replace(/%2C/g, ",");
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var NotePackSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Team folder").setDesc(
      "Path to the folder containing team member subfolders."
    ).addText(
      (text) => text.setPlaceholder("Team").setValue(this.plugin.settings.teamFolder).onChange(async (value) => {
        this.plugin.settings.teamFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setHeading().setName("Export").setDesc(
      "These settings control file exporting to write todos and recent files to the file system."
    );
    new import_obsidian4.Setting(containerEl).setName("Todo section title").setDesc("Heading text for the todo section.").addText(
      (text) => text.setPlaceholder("Open todos").setValue(this.plugin.settings.todoAnchorTitle).onChange(async (value) => {
        this.plugin.settings.todoAnchorTitle = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Recent files section title").setDesc(
      "Heading text for the recent files section."
    ).addText(
      (text) => text.setPlaceholder("Recent files").setValue(this.plugin.settings.recentFilesAnchorTitle).onChange(async (value) => {
        this.plugin.settings.recentFilesAnchorTitle = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Anchor heading level").setDesc(
      "Markdown heading level for todo and recent file sections (e.g. ##)."
    ).addDropdown(
      (dropdown) => dropdown.addOptions({
        "#": "H1 (#)",
        "##": "H2 (##)",
        "###": "H3 (###)"
      }).setValue(this.plugin.settings.anchorHeadingLevel).onChange(async (value) => {
        this.plugin.settings.anchorHeadingLevel = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Todo group heading level").setDesc(
      "Heading level for individual todo groups within the section; should be deeper than the anchor level."
    ).addDropdown(
      (dropdown) => dropdown.addOptions({
        "##": "H2 (##)",
        "###": "H3 (###)",
        "####": "H4 (####)",
        "#####": "H5 (#####)"
      }).setValue(this.plugin.settings.todoGroupHeadingLevel).onChange(async (value) => {
        this.plugin.settings.todoGroupHeadingLevel = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Recent files count").setDesc("Number of recently modified files to show.").addSlider(
      (slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.settings.recentFilesCount).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.recentFilesCount = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setHeading().setName("Sorting");
    new import_obsidian4.Setting(containerEl).setName("Show un-dated files first").setDesc("When enabled, files without a date prefix are sorted above dated files in todo views.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showUndatedFirst).onChange(async (value) => {
        this.plugin.settings.showUndatedFirst = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setHeading().setName("Due dates");
    new import_obsidian4.Setting(containerEl).setName("End of day").setDesc(
      'The time at which "end of day" due dates are considered overdue.'
    ).addDropdown((dropdown) => {
      const options = {};
      for (let h = 0; h < 24; h++) {
        const display = h === 0 ? "12:00 AM" : h < 12 ? `${h}:00 AM` : h === 12 ? "12:00 PM" : `${h - 12}:00 PM`;
        options[String(h)] = display;
      }
      dropdown.addOptions(options).setValue(String(this.plugin.settings.endOfDayHour)).onChange(async (value) => {
        this.plugin.settings.endOfDayHour = parseInt(value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("End of week").setDesc(
      'The last day of the work week for "end of week" due dates.'
    ).addDropdown(
      (dropdown) => dropdown.addOptions({
        "0": "Sunday",
        "1": "Monday",
        "2": "Tuesday",
        "3": "Wednesday",
        "4": "Thursday",
        "5": "Friday",
        "6": "Saturday"
      }).setValue(String(this.plugin.settings.endOfWeekDay)).onChange(async (value) => {
        this.plugin.settings.endOfWeekDay = parseInt(value);
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/views/myTodosView.ts
var import_obsidian6 = require("obsidian");

// src/utility/todoRenderer.ts
var import_obsidian5 = require("obsidian");
function categorizeTodos(todos) {
  const overdue = todos.filter(
    (t) => t.dueDate && getDueDateStatus(t.dueDate) === "overdue"
  );
  const dueToday = todos.filter(
    (t) => t.dueDate && getDueDateStatus(t.dueDate) === "today"
  );
  const dueSoon = todos.filter(
    (t) => t.dueDate && getDueDateStatus(t.dueDate) === "soon"
  );
  const regular = todos.filter(
    (t) => !t.dueDate || getDueDateStatus(t.dueDate) === "future"
  );
  return { overdue, dueToday, dueSoon, regular };
}
function renderCategorizedTodos(ctx, container, todos, options) {
  const { overdue, dueToday, dueSoon, regular } = categorizeTodos(todos);
  if (overdue.length > 0) {
    renderUrgentSection(ctx, container, "Overdue", overdue, "notepack-section-overdue", options);
  }
  if (dueToday.length > 0) {
    renderUrgentSection(ctx, container, "Due today", dueToday, "notepack-section-due-today", options);
  }
  if (dueSoon.length > 0) {
    renderUrgentSection(ctx, container, "Due soon", dueSoon, "notepack-section-due-soon", options);
  }
  if (regular.length > 0) {
    renderGroupedTodos(ctx, container, regular, options);
  }
}
function renderUrgentSection(ctx, container, title, todos, sectionCls, options) {
  const section = container.createDiv({
    cls: `notepack-urgency-section ${sectionCls}`
  });
  section.createDiv({ cls: "notepack-urgency-header", text: title });
  const sorted = [...todos].sort(
    (a, b) => {
      var _a, _b, _c, _d;
      return ((_b = (_a = a.dueDate) == null ? void 0 : _a.getTime()) != null ? _b : 0) - ((_d = (_c = b.dueDate) == null ? void 0 : _c.getTime()) != null ? _d : 0);
    }
  );
  renderTodoGroups(ctx, section, sorted, options, true);
}
function renderGroupedTodos(ctx, container, todos, options) {
  renderTodoGroups(ctx, container, todos, options);
}
function renderTodoGroups(ctx, container, todos, options, preserveOrder) {
  const groups = preserveOrder ? getInsertionOrderGroupNames(todos) : ctx.todoIndex.getGroupNames(todos);
  for (const group of groups) {
    const groupTodos = todos.filter((t) => t.groupName === group);
    if (groupTodos.length === 0) continue;
    const groupEl = container.createDiv({ cls: "notepack-group" });
    const groupHeader = groupEl.createDiv({ cls: "notepack-group-header" });
    const link = groupHeader.createEl("a", {
      text: group,
      cls: "notepack-group-link"
    });
    link.addEventListener("click", (e) => {
      e.preventDefault();
      void ctx.app.workspace.getLeaf(false).openFile(groupTodos[0].file).catch(console.error);
    });
    const list = groupEl.createEl("ul", { cls: "notepack-todo-list" });
    for (const todo of groupTodos) {
      void renderTodoItem(ctx, list, todo, options).catch(console.error);
    }
  }
}
function getInsertionOrderGroupNames(todos) {
  const seen = /* @__PURE__ */ new Set();
  const groups = [];
  for (const todo of todos) {
    if (!seen.has(todo.groupName)) {
      seen.add(todo.groupName);
      groups.push(todo.groupName);
    }
  }
  return groups;
}
async function renderTodoItem(ctx, list, todo, options) {
  const li = list.createEl("li", { cls: "notepack-todo-item" });
  const checkbox = li.createEl("input", { type: "checkbox" });
  checkbox.addClass("notepack-checkbox");
  checkbox.addEventListener("change", () => {
    void checkOffTodo(ctx, todo).catch(console.error);
  });
  if (options == null ? void 0 : options.showAssignee) {
    const assignee = li.createSpan({
      text: todo.assignedToAlias,
      cls: "notepack-assignee"
    });
    if (options.hideAssignee) assignee.addClass("notepack-hidden");
  }
  const text = li.createSpan({ cls: "notepack-todo-text" });
  const displayText = (options == null ? void 0 : options.showAssignee) ? todo.text.replace(/^@[A-Za-z.]+\s*/, "") : todo.text;
  await import_obsidian5.MarkdownRenderer.render(ctx.app, displayText, text, todo.file.path, ctx.component).catch(console.error);
  if (todo.dueDate) {
    const status = getDueDateStatus(todo.dueDate);
    const badge = li.createSpan({
      text: formatDueDate(todo.dueDate),
      cls: `notepack-due-badge notepack-due-${status}`
    });
    const overdueDays = getOverdueDays(todo.dueDate);
    if (overdueDays !== null) {
      badge.createSpan({
        text: ` +${formatOverdueDays(overdueDays)}`,
        cls: "notepack-overdue-count"
      });
    }
  }
}
async function checkOffTodo(ctx, todo) {
  await ctx.app.vault.process(todo.file, (content) => {
    const lines = content.split("\n");
    if (todo.lineNumber < lines.length) {
      lines[todo.lineNumber] = lines[todo.lineNumber].replace(
        /- \[ \]/,
        "- [x]"
      );
    }
    return lines.join("\n");
  });
}

// src/views/myTodosView.ts
var DISPLAY_TEXT = "My todos";
var MyTodosView = class extends import_obsidian6.ItemView {
  constructor(leaf, todoIndex) {
    super(leaf);
    this.unsubscribe = null;
    this.todoIndex = todoIndex;
  }
  getViewType() {
    return VIEW_TYPE_MY_TODOS;
  }
  getDisplayText() {
    return DISPLAY_TEXT;
  }
  getIcon() {
    return "check-square";
  }
  onOpen() {
    this.unsubscribe = this.todoIndex.onChange(() => this.render());
    this.render();
    return Promise.resolve();
  }
  onClose() {
    if (this.unsubscribe) {
      this.unsubscribe();
      this.unsubscribe = null;
    }
    return Promise.resolve();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("notepack-view");
    const header = container.createDiv({ cls: "notepack-view-header" });
    header.createEl("h4", { text: DISPLAY_TEXT });
    const todos = this.todoIndex.getMyTodos();
    if (todos.length === 0) {
      container.createDiv({
        cls: "notepack-empty",
        text: "No open todos assigned to you."
      });
      return;
    }
    const count = container.createDiv({ cls: "notepack-count" });
    count.setText(`${todos.length} open todo${todos.length !== 1 ? "s" : ""}`);
    renderCategorizedTodos(
      { app: this.app, todoIndex: this.todoIndex, component: this },
      container,
      todos
    );
  }
};

// src/views/teamTodosView.ts
var import_obsidian7 = require("obsidian");
var DISPLAY_TEXT2 = "Team todos";
var TeamTodosView = class extends import_obsidian7.ItemView {
  constructor(leaf, todoIndex, settings) {
    super(leaf);
    this.selectedMember = null;
    this.unsubscribe = null;
    this.todoIndex = todoIndex;
    this.settings = settings;
  }
  getViewType() {
    return VIEW_TYPE_TEAM_TODOS;
  }
  getDisplayText() {
    return DISPLAY_TEXT2;
  }
  getIcon() {
    return "users";
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  setSelectedMember(name) {
    this.selectedMember = name;
    this.render();
  }
  onOpen() {
    this.unsubscribe = this.todoIndex.onChange(() => this.render());
    this.render();
    return Promise.resolve();
  }
  onClose() {
    if (this.unsubscribe) {
      this.unsubscribe();
      this.unsubscribe = null;
    }
    return Promise.resolve();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("notepack-view");
    const header = container.createDiv({ cls: "notepack-view-header" });
    header.createEl("h4", { text: DISPLAY_TEXT2 });
    const folderMembers = getTeamMembers(this.app, this.settings);
    const assignedNames = this.todoIndex.getAssignedNames();
    const allMemberNames = getAllTeamMembers(folderMembers, assignedNames).map(
      (m) => m.name
    );
    if (allMemberNames.length === 0) {
      container.createDiv({
        cls: "notepack-empty",
        text: `No team members found. Create subfolders with README.md files in your "${this.settings.teamFolder}" folder or assign todos with @mentions.`
      });
      return;
    }
    const selectorRow = container.createDiv({ cls: "notepack-selector" });
    const allBtn = selectorRow.createEl("button", {
      text: "All",
      cls: `notepack-member-btn ${this.selectedMember === null ? "is-active" : ""}`
    });
    allBtn.addEventListener("click", () => {
      this.selectedMember = null;
      this.render();
    });
    for (const name of allMemberNames) {
      const btn = selectorRow.createEl("button", {
        text: name,
        cls: `notepack-member-btn ${this.selectedMember === name ? "is-active" : ""}`
      });
      if (this.todoIndex.getTodosFor(name).length > 0) {
        btn.createSpan({
          text: `${this.todoIndex.getTodosFor(name).length}`,
          cls: "notepack-member-indicator"
        });
      }
      btn.addEventListener("click", () => {
        this.selectedMember = name;
        this.render();
      });
    }
    let todos;
    if (this.selectedMember) {
      todos = this.todoIndex.getTodosFor(this.selectedMember);
    } else {
      todos = this.todoIndex.getAllTodos().filter((t) => t.assignedToAlias !== "Me");
    }
    if (todos.length === 0) {
      const msg = this.selectedMember ? `No open todos assigned to ${this.selectedMember}.` : "No open todos assigned to team members.";
      container.createDiv({ cls: "notepack-empty", text: msg });
      return;
    }
    const count = container.createDiv({ cls: "notepack-count" });
    count.setText(`${todos.length} open todo${todos.length !== 1 ? "s" : ""}`);
    renderCategorizedTodos(
      { app: this.app, todoIndex: this.todoIndex, component: this },
      container,
      todos,
      { showAssignee: true, hideAssignee: !!this.selectedMember }
    );
  }
};

// src/views/recentFilesView.ts
var import_obsidian8 = require("obsidian");
var DISPLAY_TEXT3 = "Recent files";
var RecentFilesView = class extends import_obsidian8.ItemView {
  constructor(leaf, settings) {
    super(leaf);
    this.refreshTimer = null;
    this.settings = settings;
  }
  getViewType() {
    return VIEW_TYPE_RECENT_FILES;
  }
  getDisplayText() {
    return DISPLAY_TEXT3;
  }
  getIcon() {
    return "clock";
  }
  updateSettings(settings) {
    this.settings = settings;
    this.render();
  }
  onOpen() {
    this.render();
    this.refreshTimer = window.setInterval(() => this.render(), 1e4);
    this.registerEvent(
      this.app.vault.on("modify", () => {
        window.setTimeout(() => this.render(), 1e3);
      })
    );
    return Promise.resolve();
  }
  onClose() {
    if (this.refreshTimer) {
      window.clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
    return Promise.resolve();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("notepack-view");
    const header = container.createDiv({ cls: "notepack-view-header" });
    header.createEl("h4", { text: DISPLAY_TEXT3 });
    const files = this.getRecentFiles();
    if (files.length === 0) {
      container.createDiv({
        cls: "notepack-empty",
        text: "No recently modified files found."
      });
      return;
    }
    const list = container.createEl("ul", { cls: "notepack-recent-list" });
    for (const file of files) {
      const li = list.createEl("li", { cls: "notepack-recent-item" });
      const link = li.createEl("a", {
        cls: "notepack-recent-link"
      });
      link.addEventListener("click", (e) => {
        e.preventDefault();
        void this.app.workspace.getLeaf(false).openFile(file).catch(console.error);
      });
      const nameEl = link.createDiv({ cls: "notepack-recent-name" });
      nameEl.setText(file.basename);
      const metaEl = link.createDiv({ cls: "notepack-recent-meta" });
      const parentPath = file.parent ? file.parent.path : "";
      const timeStr = this.formatRelativeTime(file.stat.mtime);
      metaEl.setText(`${parentPath ? parentPath + " \xB7 " : ""}${timeStr}`);
    }
  }
  getRecentFiles() {
    const allFiles = this.app.vault.getMarkdownFiles();
    return allFiles.filter((f) => {
      if (f.name === "README.md") return false;
      if (f.path.toLowerCase().includes("archive")) return false;
      return true;
    }).sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, this.settings.recentFilesCount);
  }
  formatRelativeTime(epochMs) {
    const now = Date.now();
    const diffMs = now - epochMs;
    const diffMin = Math.floor(diffMs / 6e4);
    const diffHour = Math.floor(diffMs / 36e5);
    const diffDay = Math.floor(diffMs / 864e5);
    if (diffMin < 1) return "Just now";
    if (diffMin < 60) return `${diffMin}m ago`;
    if (diffHour < 24) return `${diffHour}h ago`;
    if (diffDay < 7) return `${diffDay}d ago`;
    const date = new Date(epochMs);
    return date.toLocaleDateString();
  }
};

// src/modals/teamMemberModal.ts
var import_obsidian9 = require("obsidian");
var TeamMemberModal = class extends import_obsidian9.FuzzySuggestModal {
  constructor(app, settings, todoIndex, onChoose) {
    super(app);
    this.settings = settings;
    this.todoIndex = todoIndex;
    this.onChoose = onChoose;
    this.setPlaceholder("Select a team member...");
  }
  getItems() {
    const folderMembers = getTeamMembers(this.app, this.settings);
    const assignedNames = this.todoIndex.getAssignedNames();
    return getAllTeamMembers(folderMembers, assignedNames);
  }
  getItemText(member) {
    const textItems = [member.name];
    const todoCount = this.todoIndex.getTodosFor(member.name).length;
    if (todoCount > 0) {
      textItems.push(`(${todoCount})`);
    }
    return textItems.join(" ");
  }
  onChooseItem(member) {
    this.onChoose(member);
  }
};

// src/main.ts
var NotePackPlugin = class extends import_obsidian10.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.todoIndex = null;
    this.exporter = null;
  }
  async onload() {
    await this.loadSettings();
    this.todoIndex = new TodoIndex(this.app, this.settings);
    this.exporter = new TodoExporter(this.app, this.settings, this.todoIndex);
    this.registerView(VIEW_TYPE_MY_TODOS, (leaf) => {
      return new MyTodosView(leaf, this.todoIndex);
    });
    this.registerView(VIEW_TYPE_TEAM_TODOS, (leaf) => {
      return new TeamTodosView(leaf, this.todoIndex, this.settings);
    });
    this.registerView(VIEW_TYPE_RECENT_FILES, (leaf) => {
      return new RecentFilesView(leaf, this.settings);
    });
    this.addCommand({
      id: "show-my-todos",
      name: "Show my todos",
      callback: () => this.activateView(VIEW_TYPE_MY_TODOS)
    });
    this.addCommand({
      id: "show-team-todos",
      name: "Show team todos",
      callback: () => this.activateView(VIEW_TYPE_TEAM_TODOS)
    });
    this.addCommand({
      id: "show-team-member-todos",
      name: "Show team member todos",
      callback: () => {
        new TeamMemberModal(this.app, this.settings, this.todoIndex, (member) => {
          (async () => {
            await this.activateView(VIEW_TYPE_TEAM_TODOS);
            const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TEAM_TODOS);
            for (const leaf of leaves) {
              const view = leaf.view;
              view.setSelectedMember(member.name);
            }
          })().catch(console.error);
        }).open();
      }
    });
    this.addCommand({
      id: "show-recent-files",
      name: "Show recent files",
      callback: () => this.activateView(VIEW_TYPE_RECENT_FILES)
    });
    this.addCommand({
      id: "export-to-readme",
      name: "Export todos and recent files to file system",
      callback: () => this.exporter.exportAll()
    });
    this.addCommand({
      id: "rebuild-index",
      name: "Rebuild todo index",
      callback: async () => {
        await this.todoIndex.rebuild();
      }
    });
    this.addSettingTab(new NotePackSettingTab(this.app, this));
    this.addRibbonIcon("check-square", "My todos", () => {
      void this.activateView(VIEW_TYPE_MY_TODOS).catch(console.error);
    });
    this.app.workspace.onLayoutReady(async () => {
      if (this.app.metadataCache.resolvedLinks) {
        await this.todoIndex.rebuild();
      }
      this.registerEvent(
        this.app.metadataCache.on("resolved", async () => {
          if (this.todoIndex.getAllTodos().length === 0) {
            await this.todoIndex.rebuild();
          }
        })
      );
    });
    this.registerEvent(
      this.app.metadataCache.on("changed", (file, data, cache) => {
        void this.todoIndex.updateFile(file, data, cache).catch(console.error);
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian10.TFile) {
          this.todoIndex.removeFile(file.path);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.todoIndex.removeFile(oldPath);
        if (file instanceof import_obsidian10.TFile && file.extension === "md") {
          window.setTimeout(() => {
            (async () => {
              const cache = this.app.metadataCache.getFileCache(file);
              const content = await this.app.vault.cachedRead(file);
              await this.todoIndex.updateFile(file, content, cache != null ? cache : void 0);
            })().catch(console.error);
          }, 200);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian10.TFile && file.extension === "md") {
          window.setTimeout(() => {
            const cache = this.app.metadataCache.getFileCache(file);
            void this.todoIndex.updateFile(file, void 0, cache != null ? cache : void 0).catch(console.error);
          }, 200);
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.todoIndex.updateSettings(this.settings);
    this.exporter.updateSettings(this.settings);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_TEAM_TODOS)) {
      leaf.view.updateSettings(this.settings);
    }
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_RECENT_FILES)) {
      leaf.view.updateSettings(this.settings);
    }
    await this.todoIndex.rebuild();
  }
  /**
   * Activate (or focus) a sidebar view. Creates it if it doesn't exist.
   */
  async activateView(viewType) {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(viewType);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: viewType, active: true });
      }
    }
    if (leaf) {
      await workspace.revealLeaf(leaf).catch(console.error);
    }
  }
};

/* nosourcemap */